#!/bin/bash
. /usr/local/share/my_init/functions.sh

: ${postfix_fqdn:=localhost.localdomain}

: ${postfix_ssl_ca_cert_file:=/etc/ssl/certs/ca-certificates.crt}
: ${postfix_ssl_cert_file:=/etc/ssl/postfix/server.crt}
: ${postfix_ssl_key_file:=/etc/ssl/postfix/server.key}

: ${postfix_ldap_url:=ldap://ldap}
: ${postfix_ldap_tls:=yes}
: ${postfix_ldap_tls_ca_cert_file:=$postfix_ssl_ca_cert_file}
: ${postfix_ldap_tls_require_cert:=yes}
: ${postfix_ldap_basedn:=dc=ldap,dc=dit}

# default maximum is 100M
: ${postfix_message_size_limit:=104857600}

: ${postfix_internal_milters:=}
: ${postfix_external_milters:=}

docker_network=$(ip a s eth0 | sed -n '/^\s*inet \([^ ]*\).*/{s//\1/p;q}')

# set secure umask
umask 027

for var in postfix_ssl_cert_file postfix_ssl_key_file; do
    eval "$var=\"\$(mypath \$$var)\""
done
if ! [ -f "$postfix_ssl_cert_file" ]; then
    openssl req -newkey rsa:2048 -x509 -nodes -days 365 \
        -subj "/CN=$(hostname)" \
        -out "$postfix_ssl_cert_file" -keyout "$postfix_ssl_key_file"
    chmod 0644 "$postfix_ssl_cert_file"
fi

file="$(mypath /etc/ldap/ldap.passwd)"
if [ -f "$file" ]; then
    postfix_ldap_password="$(cat "$file")"
else
    echo -n "$postfix_ldap_password" > "$file"
fi

dir="$(mypath /etc/postfix/conf.d)"
mkdir -m 0755 -p "$dir"

cat > /etc/postfix/conf.d/ldap-domains.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=servers,ou=systems,$postfix_ldap_basedn
scope = one
query_filter = (&(objectClass=fdPostfixServer)(cn=$postfix_fqdn)(postfixMyDestinations=%s))
result_attribute = cn
EOF

cat > /etc/postfix/conf.d/ldap-accounts.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=people,$postfix_ldap_basedn
scope = one
query_filter = (&(objectClass=gosaMailAccount)(!(gosaMailDeliveryMode=[*I*]))(mail=%s))
result_attribute = mail
EOF

cat > /etc/postfix/conf.d/ldap-alias-distributions.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=alias,$postfix_ldap_basedn
scope = one
# postfix does not supply a time string and slapd doesn't support NOW,
# so ignore aliasExpirationdate for the moment.
query_filter = (&(objectClass=mailAliasDistribution)(gosaMailAlternateAddress=%s))
result_attribute = mail
EOF

cat > /etc/postfix/conf.d/ldap-alias-redirections.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=alias,$postfix_ldap_basedn
scope = one
# postfix does not supply a time string and slapd doesn't support NOW,
# so ignore aliasExpirationdate for the moment.
query_filter = (&(objectClass=mailAliasRedirection)(mail=%s))
result_attribute = gosaMailForwardingAddress
EOF

cat > /etc/postfix/conf.d/ldap-forward.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=people,$postfix_ldap_basedn
scope = one
query_filter = (&(objectClass=gosaMailAccount)(!(gosaMailDeliveryMode=[*I*]))(|(mail=%s)(gosaMailAlternateAddress=%s)))
result_attribute = mail,gosaMailForwardingAddress
EOF

cat > /etc/postfix/conf.d/ldap-forward-only.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=people,$postfix_ldap_basedn
scope = one
query_filter = (&(objectClass=gosaMailAccount)(gosaMailDeliveryMode=[*I*])(|(mail=%s)(gosaMailAlternateAddress=%s)))
result_attribute = gosaMailForwardingAddress
EOF

cat > /etc/postfix/conf.d/ldap-alternates.cf <<EOF
server_host = $postfix_ldap_url
version = 3
start_tls = $postfix_ldap_tls
tls_ca_cert_file = $postfix_ldap_tls_ca_cert_file
tls_require_cert = $postfix_ldap_tls_require_cert
bind = yes
bind_dn = cn=postfix,ou=dsa,$postfix_ldap_basedn
bind_pw = $postfix_ldap_password
search_base = ou=people,$postfix_ldap_basedn
scope = one
query_filter = (&(objectClass=gosaMailAccount)(!(gosaMailDeliveryMode=[*I*]))(gosaMailAlternateAddress=%s))
result_attribute = mail
EOF

chown postfix:postfix /etc/postfix/conf.d/*

# set normal umask
umask 022

echo "$postfix_fqdn" > "$(mypath /etc/mailname)"

cat > "$(mypath /etc/ldap/ldap.conf)" <<EOF
URI $postfix_ldap_url
BINDDN cn=postfix,ou=dsa,$postfix_ldap_basedn
BASE $postfix_ldap_basedn
TLS_CACERT $postfix_ldap_tls_ca_cert_file
EOF

cat > "$(mypath /etc/postfix/master.cf)" <<EOF
# ==========================================================================
# service  type  private unpriv  chroot  wakeup  maxproc command + args
#                (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
smtp       inet  n       -       y       -       1       postscreen
smtpd      pass  -       -       y       -       -       smtpd
dnsblog    unix  -       -       y       -       0       dnsblog
tlsproxy   unix  -       -       y       -       0       tlsproxy
submission inet  n       -       y       -       -       smtpd
  -o milter_macro_daemon_name=ORIGINATING
  -o syslog_name=postfix/submission
  -o smtpd_client_restrictions=
  -o smtpd_helo_restrictions=
  -o smtpd_milters=$postfix_internal_milters
  -o smtpd_recipient_restrictions=
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_sender_restrictions=
  -o smtpd_tls_eecdh_grade=ultra
  -o smtpd_tls_security_level=encrypt
  -o tls_preempt_cipherlist=yes
pickup     unix  n       -       y       60      1       pickup
cleanup    unix  n       -       y       -       0       cleanup
qmgr       unix  n       -       n       300     1       qmgr
tlsmgr     unix  -       -       y       1000?   1       tlsmgr
rewrite    unix  -       -       y       -       -       trivial-rewrite
bounce     unix  -       -       y       -       0       bounce
defer      unix  -       -       y       -       0       bounce
trace      unix  -       -       y       -       0       bounce
verify     unix  -       -       y       -       1       verify
flush      unix  n       -       y       1000?   0       flush
proxymap   unix  -       -       n       -       -       proxymap
proxywrite unix  -       -       n       -       1       proxymap
smtp       unix  -       -       y       -       -       smtp
relay      unix  -       -       y       -       -       smtp
showq      unix  n       -       y       -       -       showq
error      unix  -       -       y       -       -       error
retry      unix  -       -       y       -       -       error
discard    unix  -       -       y       -       -       discard
local      unix  -       n       n       -       -       local
virtual    unix  -       n       n       -       -       virtual
lmtp       unix  -       -       y       -       -       lmtp
anvil      unix  -       -       y       -       1       anvil
scache     unix  -       -       y       -       1       scache
EOF

cat > "$(mypath /etc/postfix/main.cf)" <<EOF
# COMPATIBILITY

compatibility_level = 2

# NOTIFICATIONS

biff = no

# INTERNET HOST AND DOMAIN NAMES

myhostname = $postfix_fqdn
myorigin = \$mydomain

# RECEIVING MAIL

mydestination =

alias_database =
alias_maps =

virtual_transport = lmtp:inet:dovecot:8025
virtual_mailbox_domains = proxy:ldap:/etc/postfix/conf.d/ldap-domains.cf
virtual_mailbox_maps = proxy:ldap:/etc/postfix/conf.d/ldap-accounts.cf
virtual_alias_maps = proxy:ldap:/etc/postfix/conf.d/ldap-alias-distributions.cf,
                     proxy:ldap:/etc/postfix/conf.d/ldap-alias-redirections.cf,
                     proxy:ldap:/etc/postfix/conf.d/ldap-forward.cf,
                     proxy:ldap:/etc/postfix/conf.d/ldap-forward-only.cf,
                     proxy:ldap:/etc/postfix/conf.d/ldap-alternates.cf

# TRUST AND RELAY CONTROL

mynetworks = 127.0.0.0/8 $docker_network
relay_domains =

# TLS parameters

tls_high_cipherlist = $(openssl_ciphers)
tls_ssl_options = NO_COMPRESSION

smtp_tls_block_early_mail_reply = yes
smtp_tls_CAfile = $postfix_ssl_ca_cert_file
smtp_tls_cert_file = $postfix_ssl_cert_file
smtp_tls_key_file = $postfix_ssl_key_file
smtp_tls_security_level = may
smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache

smtpd_tls_ask_ccert = yes
smtpd_tls_auth_only = yes
smtpd_tls_CAfile = $postfix_ssl_ca_cert_file
smtpd_tls_cert_file = $postfix_ssl_cert_file
smtpd_tls_key_file = $postfix_ssl_key_file
smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
smtpd_tls_mandatory_ciphers = high
smtpd_tls_received_header = yes
smtpd_tls_security_level = may
smtpd_tls_session_cache_database = btree:\${data_directory}/smtpd_scache
smtpd_tls_session_cache_timeout = 3600s

# AUTHENTICATION

smtpd_sasl_auth_enable = no
smtpd_sasl_authenticated_header = no
smtpd_sasl_type = dovecot
smtpd_sasl_local_domain = \$myhostname
smtpd_sasl_path = inet:dovecot:8100
smtpd_sasl_security_options = noanonymous

# ADDRESS EXTENSIONS (e.g., user+foo)

append_dot_mydomain = no
recipient_delimiter = +

# JUNK MAIL CONTROLS

disable_vrfy_command = yes
message_size_limit = $postfix_message_size_limit
smtpd_banner = \$myhostname ESMTP
smtpd_helo_required = yes
strict_rfc821_envelopes = yes

postscreen_access_list = permit_mynetworks
postscreen_greet_action = enforce

smtpd_recipient_restrictions =
    permit_mynetworks,
    reject_unauth_pipelining,
    reject_unknown_client_hostname,
    reject_invalid_helo_hostname,
    reject_non_fqdn_helo_hostname,
    reject_unknown_helo_hostname,
    reject_non_fqdn_sender,
    reject_unknown_sender_domain,
    reject_non_fqdn_recipient,
    reject_unknown_recipient_domain,
    reject_unlisted_recipient,
    reject_unauth_destination,
    permit

milter_connect_macros = i j {daemon_name} v {if_name} _
milter_default_action = accept
smtpd_milters = $postfix_external_milters
non_smtpd_milters = $postfix_internal_milters
EOF
