#!/bin/bash
. /usr/local/share/my_init/functions.sh

: ${dovecot_ssl:=required}
: ${dovecot_ssl_dh_parameters_length:=4096}
: ${dovecot_ssl_ca_cert_file:=/etc/ssl/certs/ca-certificates.crt}
: ${dovecot_ssl_cert_file:=/etc/ssl/dovecot/server.crt}
: ${dovecot_ssl_key_file:=/etc/ssl/dovecot/server.key}

: ${dovecot_ssl_client_ca_file:=$dovecot_ssl_ca_cert_file}

: ${dovecot_internal_ssl_cert_file:=$dovecot_ssl_cert_file}
: ${dovecot_internal_ssl_key_file:=$dovecot_ssl_key_file}

: ${dovecot_external_ssl_cert_file:=$dovecot_ssl_cert_file}
: ${dovecot_external_ssl_key_file:=$dovecot_ssl_key_file}

: ${dovecot_imap_ssl_cert_file:=$dovecot_external_ssl_cert_file}
: ${dovecot_imap_ssl_key_file:=$dovecot_external_ssl_key_file}

: ${dovecot_pop3_ssl_cert_file:=$dovecot_external_ssl_cert_file}
: ${dovecot_pop3_ssl_key_file:=$dovecot_external_ssl_key_file}

: ${dovecot_sieve_ssl_cert_file:=$dovecot_external_ssl_cert_file}
: ${dovecot_sieve_ssl_key_file:=$dovecot_external_ssl_key_file}

: ${dovecot_mail_replica:=}
: ${dovecot_doveadm_password:=$(pwgen -s1 32)}

: ${dovecot_ldap_url:=ldap://ldap}
: ${dovecot_ldap_tls:=yes}
: ${dovecot_ldap_tls_ca_cert_file:=$dovecot_ssl_ca_cert_file}
: ${dovecot_ldap_tls_require_cert:=hard}
: ${dovecot_ldap_basedn:=dc=ldap,dc=dit}

# set secure umask
umask 027

for var in dovecot_ssl_cert_file dovecot_ssl_key_file; do
    eval "$var=\"\$(mypath \$$var)\""
done
if ! [ -f "$dovecot_ssl_cert_file" ]; then
    openssl req -newkey rsa:2048 -x509 -nodes -days 365 \
        -subj "/CN=$(hostname)" \
        -out "$dovecot_ssl_cert_file" -keyout "$dovecot_ssl_key_file"
    chmod 0644 "$dovecot_ssl_cert_file"
fi

dir="$(mypath /var/lib/vmail)"
mkdir -m 0770 -p "$dir"
chown vmail:vmail "$dir"

file="$(mypath /etc/ldap/ldap.passwd)"
if [ -f "$file" ]; then
    dovecot_ldap_password="$(cat "$file")"
else
    echo -n "$dovecot_ldap_password" > "$file"
fi

cat > "$(mypath /etc/dovecot/dovecot-ldap.conf.ext)" <<EOF
uris = $dovecot_ldap_url
ldap_version = 3
tls = $dovecot_ldap_tls
tls_ca_cert_file = $dovecot_ldap_tls_ca_cert_file
tls_require_cert = $dovecot_ldap_tls_require_cert
dn = cn=dovecot,ou=dsa,$dovecot_ldap_basedn
dnpass = $dovecot_ldap_password
auth_bind = yes
auth_bind_userdn = uid=%u,ou=people,$dovecot_ldap_basedn
base = ou=people,$dovecot_ldap_basedn
scope = onelevel
deref = never
user_attrs = uid=user,gosaMailQuota=quota_rule=*:storage=%{ldap:gosaMailQuota}M
user_filter = (&(objectClass=gosaMailAccount)(|(uid=%u)(mail=%u)))
iterate_attrs = uid=user
iterate_filter = (objectClass=gosaMailAccount)
EOF

file=/run/secrets/dovecot_doveadm_password
[ -f "$file" ] && dovecot_doveadm_password="$(cat "$file")"

cat > "$(mypath /etc/dovecot/secrets.conf)" <<EOF
doveadm_password = $dovecot_doveadm_password
EOF

# set normal umask
umask 0022

cat > "$(mypath /etc/dovecot/dovecot.conf)" <<EOF

!include_try /etc/dovecot/secrets.conf

auth_mechanisms = plain login
auth_username_format = %Lu
disable_plaintext_auth = yes

ssl = $dovecot_ssl
ssl_protocols = !SSLv2 !SSLv3
ssl_cipher_list = $(openssl_ciphers)
ssl_prefer_server_ciphers = yes
ssl_options = no_compression
ssl_dh_parameters_length = $dovecot_ssl_dh_parameters_length
ssl_cert = <$dovecot_internal_ssl_cert_file
ssl_key = <$dovecot_internal_ssl_key_file

# not a typo, apparently no < for this param
ssl_client_ca_file = $dovecot_ssl_client_ca_file

passdb {
  driver = ldap
  args = /etc/dovecot/dovecot-ldap-passdb.conf.ext
}

userdb {
  driver = ldap
  args = /etc/dovecot/dovecot-ldap-userdb.conf.ext
}

mail_uid = vmail
mail_gid = vmail
mail_home = /var/lib/vmail/%u
mail_location = maildir:~/Maildir
mail_plugins = fts fts_solr notify quota replication

namespace inbox {
  inbox = yes
  location =
  prefix =
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Spam {
    auto = create
    special_use = \Junk
  }
  mailbox Trash {
    auto = create
    special_use = \Trash
  }
}

plugin {
  fts_autoindex = yes
  fts = solr
  fts_solr = break-imap-search url=http://solr:8983/solr/dovecot/
  fts_tika = http://tika:9998/tika/
  sieve = file:~/sieve.d;active=~/dovecot.sieve
  sieve_max_script_size = 1M
  sieve_max_actions = 256
  sieve_default = /var/lib/dovecot/default.sieve
  sieve_default_name = default
  $([ -n "$dovecot_mail_replica" ] || echo -n "#")mail_replica = tcps:$dovecot_mail_replica
}

protocols = lmtp imap pop3 sieve

# authentication
################

service auth {
  inet_listener {
    port = 8100
  }

  unix_listener auth-userdb {
    group = vmail
  }
}

# lmtp
######

service lmtp {
  user = vmail
  inet_listener lmtp {
    port = 8025
  }
}

protocol lmtp {
  deliver_log_format = msgid=%m: %$
  mail_plugins = \$mail_plugins sieve
  postmaster_address = postmaster
  quota_full_tempfail = yes
  rejection_reason = Your message to <%t> was automatically rejected:%n%r
}

# imap
######

service imap-login {
  inet_listener imaps {
    # disable the imaps service
    port = 0
  }
}

protocol imap {
  imap_client_workarounds = delay-newmail
  mail_max_userip_connections = 10
  mail_plugins = \$mail_plugins imap_quota
  ssl_cert = <$dovecot_imap_ssl_cert_file
  ssl_key = <$dovecot_imap_ssl_key_file
}

# pop3
######

service pop3-login {
  inet_listener pop3s {
    # disable the pop3s service
    port = 0
  }
}

protocol pop3 {
  pop3_client_workarounds = outlook-no-nuls oe-ns-eoh
  mail_max_userip_connections = 10
  ssl_cert = <$dovecot_pop3_ssl_cert_file
  ssl_key = <$dovecot_pop3_ssl_key_file
}

# replication
#############

service aggregator {
  fifo_listener replication-notify-fifo {
    user = vmail
  }
  unix_listener replication-notify {
    user = vmail
  }
}

service replicator {
  process_min_avail = 1
  unix_listener replicator-doveadm {
    mode = 0660
    group = vmail
  }
}

# doveadm (needed for replication)
##################################

# client port
doveadm_port = 9027

service doveadm {
  inet_listener {
    port = 9027
    ssl = yes
  }
}

# managesieve
#############

protocol sieve {
  ssl_cert = <$dovecot_sieve_ssl_cert_file
  ssl_key = <$dovecot_sieve_ssl_key_file
}
EOF
