#!/bin/bash

: ${dovecot_ssl:=required}
: ${dovecot_ssl_dh_parameters_length:=4096}
: ${dovecot_ssl_cert_file:=/etc/ssl/dovecot/dovecot.crt}
: ${dovecot_ssl_key_file:=/etc/ssl/dovecot/dovecot.key}
: ${dovecot_ssl_client_ca_file:=/etc/ssl/certs/ca-certificates.crt}

: ${dovecot_mail_replica:=}
: ${dovecot_doveadm_password:=$(pwgen -s1 32)}

: ${dovecot_ldap_url:=ldap://ldap}
: ${dovecot_ldap_tls:=yes}
: ${dovecot_ldap_tls_ca_cert_file:=$dovecot_ssl_client_ca_file}
: ${dovecot_ldap_tls_require_cert:=hard}
: ${dovecot_ldap_basedn:=dc=ldap,dc=dit}
: ${dovecot_ldap_password:=password}

# set secure umask
umask 0227

if ! [ -f "$dovecot_ssl_cert_file" ]; then
    openssl req -newkey rsa:2048 -x509 -nodes -days 365 \
        -subj "/CN=$(hostname)" \
        -out $dovecot_ssl_cert_file -keyout $dovecot_ssl_key_file
fi

cat > /etc/dovecot/dovecot-ldap.conf.ext <<EOF
uris = $dovecot_ldap_url
ldap_version = 3
tls = $dovecot_ldap_tls
tls_ca_cert_file = $dovecot_ldap_tls_ca_cert_file
tls_require_cert = $dovecot_ldap_tls_require_cert
dn = cn=dovecot,ou=dsa,$dovecot_ldap_basedn
dnpass = $dovecot_ldap_password
auth_bind = yes
auth_bind_userdn = uid=%u,ou=people,$dovecot_ldap_basedn
base = ou=people,$dovecot_ldap_basedn
scope = onelevel
deref = never
user_attrs = uid=user,gosaMailQuota=quota_rule=*:storage=%{ldap:gosaMailQuota}M
user_filter = (&(objectClass=gosaMailAccount)(|(uid=%u)(mail=%u)))
iterate_attrs = uid=user
iterate_filter = (objectClass=gosaMailAccount)
EOF
ln -s dovecot-ldap.conf.ext /etc/dovecot/dovecot-ldap-passdb.conf.ext
ln -s dovecot-ldap.conf.ext /etc/dovecot/dovecot-ldap-userdb.conf.ext

[ -n "$dovecot_mail_replica" ] && cat > /etc/dovecot/conf.d/replica.conf <<EOF

# not a typo, apparently no < for this param
#ssl_client_ca_file = $dovecot_ssl_client_ca_file

mail_plugins = notify replication

doveadm_port = 9027
doveadm_password = $dovecot_doveadm_password

plugin {
  mail_replica = tcp:$dovecot_mail_replica
}

service aggregator {
  fifo_listener replication-notify-fifo {
    user = vmail
  }
  unix_listener replication-notify {
    user = vmail
  }
}

service replicator {
  process_min_avail = 1
  unix_listener replicator-doveadm {
    mode = 0660
    group = vmail
  }
}

service doveadm {
  inet_listener {
    port = $dovecot_doveadm_port
    ssl = yes
  }
}
EOF

# set normal umask
umask 0022

cat > /etc/dovecot/conf.d/ssl.conf <<EOF
ssl = $dovecot_ssl
ssl_protocols = !SSLv2 !SSLv3
ssl_cipher_list = EECDH+AESGCM:EDH+AESGCM:EECDH+AES256:EDH+AES256
ssl_prefer_server_ciphers = yes
ssl_options = no_compression
ssl_dh_parameters_length = $dovecot_ssl_dh_parameters_length
ssl_cert = <$dovecot_ssl_cert_file
ssl_key = <$dovecot_ssl_key_file
EOF

docker_network=$(ip a s eth0 | sed -n '/^\s*inet \([^ ]*\).*/{s//\1/p;q}')
cat > /etc/dovecot/conf.d/trusted_networks.conf <<EOF
login_trusted_networks = 127.0.0.0/8 $docker_network
EOF
