version: '2'

services:

  postfix:
    image: marklee77/postfix
    depends_on:
      - dovecot
      - ldap
      - db
      - clamav
      - spamd
    links:
      - dovecot

  dovecot:
    image: marklee77/dovecot
    depends_on:
      - ldap
      - solr
      - tika
    links:
      - ldap
      - solr
      - tika

  solr:
    image: marklee77/solr

  tika:
    image: logicalspark/docker-tikaserver

  ldap:
    image: marklee77/fusiondirectory

  db:
    image: postgres

  clamav:
    image: marklee77/clamav

  spamd:
    image: marklee77/spamd

