version: '2'

services:

  postfix:
    image: marklee77/postfix
    build: postfix
    depends_on:
      - dovecot
      - clamav
      - spamd

  dovecot:
    image: marklee77/dovecot
    build: dovecot
    depends_on:
      - solr
      - tika

  solr:
    image: marklee77/solr
    build: solr

  tika:
    image: logicalspark/docker-tikaserver

  clamav:
    image: marklee77/clamav
    build: clamav

  spamd:
    image: marklee77/spamd
    build: spamd
