version: '2'
services:
  postfix:
    build: postfix
    depends_on:
      - dovecot
      - ldap
      - db
    links:
      - dovecot

  dovecot:
    build: dovecot
    depends_on:
      - ldap
      - solr
    links:
      - ldap
      - solr
    volumes:
      - ./test:/var/vmail/test
    ports:
      - "143:143"
    environment:
      dovecot_require_ssl: 'no'
      dovecot_ldap_password: "$dovecot_ldap_password"

  solr:
    build: solr

  ldap:
    image: marklee77/slapd-auth
    environment:
      slapd_require_ssl: 'no'

  db:
    image: postgres
