version: '2'

services:
  postfix:
    build: postfix
    depends_on:
      - dovecot
      - ldap
      - db
    links:
      - dovecot
    environment:
      postfix_ldap_password:
      postfix_ldap_tls: 'no'

  dovecot:
    build: dovecot
    depends_on:
      - ldap
      - solr
    links:
      - ldap
      - solr
    volumes:
      - ./test:/var/vmail/test
    ports:
      - "143:143"
    environment:
      dovecot_ldap_password:
      dovecot_ldap_tls: 'no'

  solr:
    build: solr

  #tika:
  #  image: logicalspark/docker-tikaserver

  ldap:
    image: marklee77/slapd-auth
    environment:
      slapd_admin_password:
      slapd_require_ssl: 'no'

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD:
