version: '2'
services:
  postfix:
    build: postfix
    links:
      - dovecot

  dovecot:
    build: dovecot
    links:
      - solr
    volumes:
      - ./test:/var/mail/test
    ports:
      - "143:143"

  solr:
    build: solr
