postfix:
  build: postfix
  links:
    - dovecot
    - mysql

dovecot:
  build: dovecot
  links:
    - mysql
    - solr

mysql:
  image: mariadb
  volumes:
    - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_POSTFIX_PASSWORD=password

solr:
  build: solr
