version: '2'
services:
  postfix:
    build: postfix
    links:
      - dovecot

  dovecot:
    build: dovecot
    links:
      - ldap
      - solr
    volumes:
      - ./test:/var/vmail/test
    ports:
      - "143:143"

  solr:
    build: solr

  ldap:
    image: marklee77/slapd-auth
