version: '2'

services:

  postfix:
    image: marklee77/postfix
    build: postfix
    depends_on:
      - dovecot

  dovecot:
    image: marklee77/dovecot
    build: dovecot
    depends_on:
      - solr
      - tika

  solr:
    image: marklee77/solr-dovecot
    build: solr

  tika:
    image: logicalspark/docker-tikaserver
