#!/bin/sh
. /usr/local/share/my_init/functions.sh

: ${opendkim_selector_prefix:=default}
: ${opendkim_sign_domains:=}
: ${opendkim_internal_networks:=$(ip route show | awk '$2 != "via" { print $1 }' | paste -sd' ')}

mkdir -m 0770 -p /var/run/opendkim
chown opendkim:opendkim /var/run/opendkim

mkdir -m 0770 -p /var/lib/opendkim/keys
chown opendkim:opendkim /var/lib/opendkim/keys

# set normal umask
umask 022

: > /var/lib/opendkim/domains.txt
for domain in $opendkim_sign_domains; do
    echo "$domain" >> /var/lib/opendkim/domains.txt
done

echo -n "$opendkim_selector_prefix" > /var/lib/opendkim/prefix.txt

while true; do
    echo "attempting to update dkim-keys if necessary..."
    /usr/local/sbin/rotate-dkim-keys
    ls /var/lib/opendkim/keys/*.txt >/dev/null 2>&1 && break
    sleep 10
done

file=/var/lib/opendkim/InternalHosts
if ! [ -f "$file" ]; then
    echo "127.0.0.1" > "$file"
    for network in $opendkim_internal_networks; do
        echo "$network" >> "$file"
    done
fi
