#!/bin/sh
. /usr/local/share/my_init/functions.sh

: ${opendkim_sign_domains:=}

mkdir -m 0770 -p /var/run/opendkim
chown opendkim:opendkim /var/run/opendkim

mkdir -m 0770 -p /var/lib/opendkim/keys
chown opendkim:opendkim /var/lib/opendkim/keys

# set normal umask
umask 022

: > /var/lib/opendkim/domains.txt
for domain in $opendkim_sign_domains; do
    echo "$domain" >> /var/lib/opendkim/domains.txt
done

: >/var/lib/opendkim/SigningTable

: >/var/lib/opendkim/KeyTable
