#!/bin/sh

: ${rspamd_clamav_servers:=clamav}
: ${rspamd_redis_servers:=redis}

file=/run/secrets/rspamd_controller_password
[ -f "$file" ] && rspamd_controller_password="$(cat "$file")"

: ${rspamd_controller_password:=$(pwgen -s1 32)}

# set secure umask
umask 277

cat >/etc/rspamd/local.d/worker-controller.inc <<EOF
password = "$(rspamadm pw -p "$rspamd_controller_password")";
bind_socket = "*:80";
EOF
chown rspamd:rspamd /etc/rspamd/local.d/worker-controller.inc

# set normal umask
umask 222

cat >/etc/rspamd/local.d/antivirus.conf <<EOF
clamav {
  servers = "$rspamd_clamav_servers";
}
EOF
chown rspamd:rspamd /etc/rspamd/local.d/antivirus.conf

cat >/etc/rspamd/local.d/classifier-bayes.conf <<EOF
backend = "redis";
EOF
chown rspamd:rspamd /etc/rspamd/local.d/classifier-bayes.conf

cat >/etc/rspamd/local.d/logging.inc <<EOF
type = "syslog";
level = "info";
EOF
chown rspamd:rspamd /etc/rspamd/local.d/logging.inc

cat >/etc/rspamd/local.d/milter_headers.conf <<EOF
skip_local = false;
use = ["x-spam-level", "x-spam-status", "authentication-results"];
EOF
chown rspamd:rspamd /etc/rspamd/local.d/milter_headers.conf

cat >/etc/rspamd/local.d/metrics.conf <<EOF
actions {
  greylist = 2; # lower threshold for greylisting
}

group "antivirus" {
  symbol "CLAM_VIRUS" {
    weight = 20.0;
    one_shot = true;
  }
}
EOF
chown rspamd:rspamd /etc/rspamd/local.d/metrics.conf

cat >/etc/rspamd/local.d/redis.conf <<EOF
servers = "$rspamd_redis_servers";
EOF
chown rspamd:rspamd /etc/rspamd/local.d/redis.conf

cat >/etc/rspamd/local.d/worker-proxy.inc <<EOF
bind_socket = "*:1025";
EOF
chown rspamd:rspamd /etc/rspamd/local.d/worker-proxy.inc
